# Generated by Django 4.2.11 on 2024-04-07 11:16

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import qiniuupload.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("agreement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorksCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="分类名称", max_length=30, verbose_name="分类名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
            ],
            options={
                "verbose_name": "分类管理",
                "verbose_name_plural": "分类管理",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="WorksState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="状态名称", max_length=30, verbose_name="状态名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
            ],
            options={
                "verbose_name": "状态管理",
                "verbose_name_plural": "状态管理",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Works",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(db_comment="标题", max_length=200, verbose_name="标题"),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True,
                        db_comment="医院",
                        max_length=100,
                        null=True,
                        verbose_name="医院",
                        editable=False,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_comment="手机号",
                        max_length=11,
                        null=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "video_upload",
                    qiniuupload.fields.QiniuField(
                        blank=True,
                        db_comment="文件上传",
                        max_length=512,
                        null=True,
                        verbose_name="文件上传",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, db_comment="支付时间", null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "is_push",
                    models.BooleanField(
                        db_comment="是否已推送",
                        default=False,
                        verbose_name="是否已推送",
                    ),
                ),
                (
                    "sale_name",
                    models.CharField(
                        blank=True,
                        db_comment="销售姓名",
                        max_length=50,
                        null=True,
                        verbose_name="销售姓名",
                    ),
                ),
                (
                    "content",
                    DjangoUeditor.models.UEditorField(
                        blank=True, db_comment="内容", null=True, verbose_name="内容"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        db_comment="作者",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.doctor",
                        verbose_name="作者",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_comment="素材类型",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.workscategory",
                        verbose_name="素材类型",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        db_comment="劳务费档位",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agreement.laborfeelevel",
                        verbose_name="劳务费档位",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        db_comment="状态",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.worksstate",
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "作品管理",
                "verbose_name_plural": "作品管理",
                "ordering": ["-pk"],
            },
        ),
    ]
