# Generated by Django 4.2.11 on 2024-04-10 11:02

from django.db import migrations, models
import django.db.models.deletion
import qiniuupload.fields


class Migration(migrations.Migration):

    dependencies = [
        ("agreement", "0001_initial"),
        ("user", "0002_doctor_bank_doctor_bank_card_number_and_more"),
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseWorksCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="分类名称", max_length=30, verbose_name="分类名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
            ],
            options={
                # "verbose_name": "病例分类管理",
                # "verbose_name_plural": "病例分类管理",
                "verbose_name": "疾病认知分类管理",
                "verbose_name_plural": "疾病认知分类管理",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="CaseWorksState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="状态名称", max_length=30, verbose_name="状态名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
            ],
            options={
                # "verbose_name": "病例状态管理",
                # "verbose_name_plural": "病例状态管理",
                "verbose_name": "疾病认知状态管理",
                "verbose_name_plural": "疾病认知状态管理",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_comment="标题",
                        max_length=30,
                        null=True,
                        verbose_name="标题",
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True,
                        db_comment="医院",
                        max_length=100,
                        null=True,
                        verbose_name="医院",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_comment="手机号",
                        max_length=11,
                        null=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_comment="素材类型",
                        default="病历",
                        editable=False,
                        max_length=2,
                        verbose_name="素材类型",
                    ),
                ),
                (
                    "video_upload",
                    qiniuupload.fields.QiniuField(
                        blank=True,
                        db_comment="文件上传",
                        max_length=512,
                        null=True,
                        verbose_name="文件上传",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True, db_comment="支付时间", null=True, verbose_name="支付时间"
                    ),
                ),
                (
                    "is_push",
                    models.BooleanField(
                        db_comment="是否已推送", default=False, verbose_name="是否已推送"
                    ),
                ),
                (
                    "sale_name",
                    models.CharField(
                        blank=True,
                        db_comment="销售姓名",
                        max_length=50,
                        null=True,
                        verbose_name="销售姓名",
                    ),
                ),
                (
                    "sex",
                    models.SmallIntegerField(
                        choices=[(0, "男女"), (1, "女")],
                        db_comment="性别",
                        verbose_name="性别",
                    ),
                ),
                ("age", models.SmallIntegerField(db_comment="年龄", verbose_name="年龄")),
                (
                    "case_now",
                    models.CharField(
                        db_comment="现病史", max_length=350, verbose_name="现病史"
                    ),
                ),
                (
                    "sle",
                    models.CharField(
                        db_comment="SLE病变部位", max_length=350, verbose_name="SLE病变部位"
                    ),
                ),
                (
                    "case_time",
                    models.DateTimeField(db_comment="发病时间", verbose_name="发病时间"),
                ),
                (
                    "history_scheme",
                    models.CharField(
                        db_comment="既往治疗方案", max_length=350, verbose_name="既往治疗方案"
                    ),
                ),
                (
                    "now_scheme",
                    models.CharField(
                        db_comment="现今治疗方案", max_length=350, verbose_name="现今治疗方案"
                    ),
                ),
                (
                    "metrics",
                    models.CharField(
                        db_comment="关键检测指标", max_length=1200, verbose_name="关键检测指标"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_comment="作者",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.doctor",
                        verbose_name="作者",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        db_comment="劳务费档位",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agreement.laborfeelevel",
                        verbose_name="劳务费档位",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_comment="状态",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.caseworksstate",
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                # "verbose_name": "病例征集",
                # "verbose_name_plural": "病例征集",
                "verbose_name": "疾病认知调研",
                "verbose_name_plural": "疾病认知调研",
                "ordering": ["-pk"],
            },
        ),
    ]
