# Generated by Django 4.2.11 on 2024-04-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0002_caseworkscategory_caseworksstate_case"),
    ]

    operations = [
        migrations.DeleteModel(name="CaseWorksCategory",),
        migrations.RemoveField(model_name="case", name="video_upload",),
        migrations.AlterField(
            model_name="case",
            name="sex",
            field=models.SmallIntegerField(
                choices=[(0, "男"), (1, "女")], db_comment="性别", verbose_name="性别"
            ),
        ),
    ]
