# Generated by Django 4.2.11 on 2024-05-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0003_delete_caseworkscategory_remove_case_video_upload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="payment_amount",
            field=models.FloatField(
                db_comment="支付金额", default=0.0, verbose_name="支付金额"
            ),
        ),
        migrations.AddField(
            model_name="works",
            name="payment_amount",
            field=models.FloatField(
                db_comment="支付金额", default=0.0, verbose_name="支付金额"
            ),
        ),
    ]
