# Generated by Django 4.2.11 on 2024-05-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0004_case_payment_amount_works_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="payment_amount",
            field=models.DecimalField(
                db_comment="支付金额",
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="支付金额",
            ),
        ),
        migrations.AlterField(
            model_name="works",
            name="payment_amount",
            field=models.DecimalField(
                db_comment="支付金额",
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="支付金额",
            ),
        ),
    ]
