# Generated by Django 4.2.11 on 2024-06-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0005_alter_case_payment_amount_alter_works_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="category",
            field=models.CharField(
                choices=[("SLE/LN", "SLE/LN"), ("MG", "MG")],
                db_comment="素材类型",
                default="SLE/LN",
                editable=False,
                max_length=12,
                verbose_name="素材类型",
            ),
        ),
    ]
