# Generated by Django 4.2.16 on 2024-10-22 17:49

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_doctor_bank_doctor_bank_card_number_and_more"),
        ("agreement", "0001_initial"),
        ("works", "0006_alter_case_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="疾病名称", max_length=100, verbose_name="疾病名称"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        # help_text="病例提交顶部备注",
                        help_text="疾病认知提交顶部备注",
                        max_length=255,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "body",
                    DjangoUeditor.models.UEditorField(
                        db_comment="介绍", verbose_name="介绍"
                    ),
                ),
                (
                    "is_use",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序",
                        default=0,
                        help_text="倒序",
                        verbose_name="排序",
                    ),
                ),
            ],
            options={
                "verbose_name": "疾病管理",
                "verbose_name_plural": "疾病管理",
                "ordering": ["-order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        db_comment="调研范围", max_length=30, verbose_name="调研范围"
                    ),
                ),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "短填空"),
                            (2, "长填空"),
                            (3, "单选"),
                            (4, "多选"),
                            (5, "日期"),
                            (6, "上传图片"),
                        ],
                        db_comment="题目类型",
                        db_index=True,
                        default=1,
                        max_length=2,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="题目名称", max_length=100, verbose_name="题目名称"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        db_comment="单位/备注",
                        max_length=100,
                        null=True,
                        verbose_name="单位/备注",
                    ),
                ),
                (
                    "is_use",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        db_comment="是否必填", default=True, verbose_name="是否必填"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序",
                        default=0,
                        help_text="倒序",
                        verbose_name="排序",
                    ),
                ),
            ],
            options={
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="选项名称", max_length=100, verbose_name="选项名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序",
                        default=0,
                        help_text="倒叙",
                        verbose_name="排序",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_comment="题目",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="works.question",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="MedCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True,
                        db_comment="医院",
                        max_length=100,
                        null=True,
                        verbose_name="医院",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_comment="手机号",
                        max_length=11,
                        null=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("SLE/LN", "SLE/LN"), ("MG", "MG")],
                        db_comment="素材类型",
                        default="SLE/LN",
                        editable=False,
                        max_length=12,
                        verbose_name="素材类型",
                    ),
                ),
                (
                    "payment_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="支付时间",
                        null=True,
                        verbose_name="支付时间",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        db_comment="支付金额",
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="支付金额",
                    ),
                ),
                (
                    "is_push",
                    models.BooleanField(
                        db_comment="是否已推送",
                        default=False,
                        verbose_name="是否已推送",
                    ),
                ),
                (
                    "sale_name",
                    models.CharField(
                        blank=True,
                        db_comment="销售姓名",
                        max_length=50,
                        null=True,
                        verbose_name="销售姓名",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        # db_comment="表单病例收集", verbose_name="表单病例收集"
                        db_comment="表单疾病认知收集", verbose_name="表单疾病认知收集"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_comment="作者",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_med_cases",
                        to="user.doctor",
                        verbose_name="作者",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        blank=True,
                        db_comment="疾病",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dis_med_cases",
                        to="works.disease",
                        verbose_name="疾病",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        db_comment="劳务费档位",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agreement.laborfeelevel",
                        verbose_name="劳务费档位",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_comment="状态",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.caseworksstate",
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                # "verbose_name": "新病例征集",
                # "verbose_name_plural": "新病例征集",
                "verbose_name": "新疾病认知调研",
                "verbose_name_plural": "新疾病认知调研",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="questions",
            field=models.ManyToManyField(
                related_name="question_diseases",
                to="works.question",
                verbose_name="题目",
            ),
        ),
    ]
