# Generated by Django 4.2.16 on 2024-10-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0007_disease_question_option_medcase_disease_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="scope",
        ),
        migrations.AlterField(
            model_name="question",
            name="kind",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "短填空"),
                    (2, "长填空"),
                    (3, "单选"),
                    (4, "多选"),
                    (5, "日期"),
                    (6, "上传图片"),
                ],
                db_comment="题目类型",
                db_index=True,
                default=1,
                verbose_name="题目类型",
            ),
        ),
    ]
