# Generated by Django 4.2.16 on 2024-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0008_remove_question_scope_alter_question_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["-order", "-id"],
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-order", "-id"],
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
            },
        ),
        migrations.RemoveField(
            model_name="medcase",
            name="category",
        ),
        migrations.RemoveField(
            model_name="medcase",
            name="hospital",
        ),
        migrations.RemoveField(
            model_name="medcase",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="medcase",
            name="sale_name",
        ),
        migrations.AlterField(
            model_name="disease",
            name="questions",
            field=models.ManyToManyField(
                blank=True,
                related_name="question_diseases",
                to="works.question",
                verbose_name="题目",
            ),
        ),
    ]
