# Generated by Django 4.2.16 on 2024-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0009_alter_option_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["order", "-id"],
                "verbose_name": "题库",
                "verbose_name_plural": "题库",
            },
        ),
        migrations.AlterField(
            model_name="medcase",
            name="data",
            field=models.JSONField(
                # db_comment="表单病例收集", editable=False, verbose_name="表单病例收集"
                db_comment="表单疾病认知收集", editable=False, verbose_name="表单疾病认知收集"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.IntegerField(
                db_comment="排序", default=0, help_text="正序", verbose_name="排序"
            ),
        ),
    ]
