# Generated by Django 4.2.16 on 2024-10-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0010_alter_question_options_alter_medcase_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                db_comment="题目",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="works.question",
                verbose_name="题目",
            ),
        ),
    ]
