# Generated by Django 4.2.16 on 2024-10-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0011_alter_option_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="选项名称", max_length=100, verbose_name="选项名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序",
                        default=0,
                        help_text="倒序",
                        verbose_name="排序",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_comment="题目",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="works.question",
                        verbose_name="题目",
                    ),
                ),
            ],
            options={
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
                "ordering": ["-order", "-id"],
            },
        ),
        migrations.DeleteModel(
            name="Option",
        ),
    ]
