# Generated by Django 4.2.11 on 2024-04-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        db_comment="微信openid",
                        editable=False,
                        max_length=128,
                        null=True,
                        verbose_name="微信openid",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_comment="手机号码", max_length=11, verbose_name="手机号码"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="医生姓名", max_length=10, verbose_name="医生姓名"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(db_comment="医院", max_length=30, verbose_name="医院"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True,
                        db_comment="省份",
                        max_length=30,
                        null=True,
                        verbose_name="省份",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="大区",
                        max_length=30,
                        null=True,
                        verbose_name="大区",
                    ),
                ),
                (
                    "precinct",
                    models.CharField(
                        blank=True,
                        db_comment="片区",
                        max_length=30,
                        null=True,
                        verbose_name="片区",
                    ),
                ),
                (
                    "pic",
                    models.URLField(
                        blank=True,
                        db_comment="行医执照",
                        max_length=250,
                        null=True,
                        verbose_name="行医执照",
                    ),
                ),
                (
                    "state",
                    models.SmallIntegerField(
                        choices=[(0, "初始化"), (1, "待审核"), (2, "已认证"), (3, "不通过")],
                        db_comment="认证状态",
                        default=0,
                        verbose_name="认证状态",
                    ),
                ),
                (
                    "cause",
                    models.CharField(
                        blank=True,
                        db_comment="审核不通过的原因",
                        max_length=100,
                        null=True,
                        verbose_name="审核不通过的原因",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        db_comment="最后登录时间",
                        editable=False,
                        null=True,
                        verbose_name="最后登录时间",
                    ),
                ),
                (
                    "is_subscribe",
                    models.BooleanField(
                        db_comment="关注公众号",
                        default=False,
                        editable=False,
                        verbose_name="关注公众号",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生信息",
                "verbose_name_plural": "医生信息",
                "ordering": ["-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="doctor",
            constraint=models.UniqueConstraint(
                fields=("phone", "openid"), name="unique_doctor_phone_openid"
            ),
        ),
    ]
