# Generated by Django 4.2.11 on 2024-04-10 10:10

from django.db import migrations, models
import xadmin.expand_model_fields


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="bank",
            field=models.CharField(
                blank=True, db_comment="银行", max_length=100, null=True, verbose_name="银行"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="bank_card_number",
            field=xadmin.expand_model_fields.EncryptedCharField(
                blank=True,
                db_comment="银行卡号",
                max_length=600,
                null=True,
                verbose_name="银行卡号",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="bank_operation_name",
            field=models.CharField(
                blank=True,
                db_comment="开户行名称",
                max_length=50,
                null=True,
                verbose_name="开户行名称",
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="card_number",
            field=xadmin.expand_model_fields.EncryptedCharField(
                blank=True,
                db_comment="身份证号码",
                max_length=600,
                null=True,
                verbose_name="身份证号码",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="phone",
            field=models.CharField(
                db_comment="手机号码", max_length=11, unique=True, verbose_name="手机号码"
            ),
        ),
    ]
