# Generated by Django 4.2.23 on 2025-08-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor_bank_doctor_bank_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, db_comment='医院', max_length=30, null=True, verbose_name='医院'),
        ),
    ]
