# Generated by Django 3.2.14 on 2022-12-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
        ('reversion', '0002_auto_20221202_1707'),
    ]

    operations = [
    ]
