# Generated by Django 3.2.16 on 2022-12-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0003_merge_20221206_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='version',
            name='revision',
            field=models.ForeignKey(help_text='The revision that contains this version.', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='reversion.revision'),
        ),
    ]
