# Generated by Django 4.2.11 on 2024-07-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agreement", "0001_initial"),
        ("user", "0002_doctor_bank_doctor_bank_card_number_and_more"),
        ("works", "0006_alter_case_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseasesCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="分类名称", max_length=30, verbose_name="分类名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
                (
                    "is_use",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
            ],
            options={
                "verbose_name": "疾病分类",
                "verbose_name_plural": "疾病分类",
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="选项名称", max_length=100, verbose_name="选项名称"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        db_comment="排序", default=0, help_text="倒叙", verbose_name="排序"
                    ),
                ),
            ],
            options={"verbose_name": "选项", "verbose_name_plural": "选项",},
        ),
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        db_comment="调研范围", max_length=30, verbose_name="调研范围"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("S", "单选题"),
                            ("D", "多选题"),
                            ("P", "评分题"),
                            ("T", "排序题"),
                        ],
                        db_comment="题目类型",
                        max_length=2,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="题目名称", max_length=100, verbose_name="题目名称"
                    ),
                ),
                (
                    "is_use",
                    models.BooleanField(
                        db_comment="是否启用", default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        db_comment="分类",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.diseasescategory",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={"verbose_name": "题库", "verbose_name_plural": "题库",},
        ),
        migrations.CreateModel(
            name="CommitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "hospital",
                    models.CharField(
                        blank=True,
                        db_comment="医院",
                        max_length=100,
                        null=True,
                        verbose_name="医院",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_comment="手机号",
                        max_length=11,
                        null=True,
                        verbose_name="手机号",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        db_comment="提交的答题数据", editable=False, verbose_name="提交数据"
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        db_comment="劳务费档位",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agreement.laborfeelevel",
                        verbose_name="劳务费档位",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        db_comment="状态",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="works.worksstate",
                        verbose_name="状态",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_comment="用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.doctor",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={"verbose_name": "提交记录", "verbose_name_plural": "提交记录",},
        ),
    ]
