# Generated by Django 4.2.11 on 2024-07-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                db_comment="题目",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="survey.questionbank",
                verbose_name="题目",
            ),
        ),
    ]
