# Generated by Django 4.2.11 on 2024-07-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_option_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["-order"],
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
            },
        ),
        migrations.AlterField(
            model_name="questionbank",
            name="kind",
            field=models.CharField(
                choices=[("S", "单选题"), ("D", "多选题"), ("P", "评分题"), ("T", "排序题")],
                db_comment="题目类型",
                db_index=True,
                max_length=2,
                verbose_name="题目类型",
            ),
        ),
    ]
