# Generated by Django 4.2.11 on 2024-07-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_alter_option_options_alter_questionbank_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitlog",
            name="category",
            field=models.ForeignKey(
                db_comment="分类",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="survey.diseasescategory",
                verbose_name="分类",
            ),
        ),
    ]
