# Generated by Django 4.2.11 on 2024-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0004_commitlog_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitlog",
            name="payment_amount",
            field=models.DecimalField(
                db_comment="支付金额",
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="支付金额",
            ),
        ),
        migrations.AddField(
            model_name="commitlog",
            name="payment_time",
            field=models.DateTimeField(
                blank=True, db_comment="支付时间", null=True, verbose_name="支付时间"
            ),
        ),
    ]
