# Generated by Django 4.2.11 on 2024-04-07 11:16

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaborFeeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(db_comment="档位", verbose_name="档位"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True,
                        db_comment="备注",
                        max_length=32,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "激活"), (2, "禁用")],
                        db_comment="状态",
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "劳务费档位",
                "verbose_name_plural": "劳务费档位",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_comment="创建时间", verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_comment="更新时间", verbose_name="更新时间"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_comment="条款名称", max_length=64, verbose_name="条款名称"
                    ),
                ),
                (
                    "content",
                    DjangoUeditor.models.UEditorField(
                        db_comment="条款正文", verbose_name="条款正文"
                    ),
                ),
                (
                    "state",
                    models.PositiveIntegerField(
                        choices=[(1, "激活"), (2, "禁用")],
                        db_comment="条款状态",
                        default=1,
                        verbose_name="条款状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "隐私条款",
                "verbose_name_plural": "隐私条款",
                "ordering": ["-pk"],
            },
        ),
    ]
